//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Import
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Nova_estruturaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Nova_estruturaEntities object using the connection string found in the 'Nova_estruturaEntities' section of the application configuration file.
        /// </summary>
        public Nova_estruturaEntities() : base("name=Nova_estruturaEntities", "Nova_estruturaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Nova_estruturaEntities object.
        /// </summary>
        public Nova_estruturaEntities(string connectionString) : base(connectionString, "Nova_estruturaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Nova_estruturaEntities object.
        /// </summary>
        public Nova_estruturaEntities(EntityConnection connection) : base(connection, "Nova_estruturaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sacados2> sacados2
        {
            get
            {
                if ((_sacados2 == null))
                {
                    _sacados2 = base.CreateObjectSet<sacados2>("sacados2");
                }
                return _sacados2;
            }
        }
        private ObjectSet<sacados2> _sacados2;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sacados2 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosacados2(sacados2 sacados2)
        {
            base.AddObject("sacados2", sacados2);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Nova_estruturaModel", Name="sacados2")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sacados2 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sacados2 object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static sacados2 Createsacados2(global::System.Int32 id)
        {
            sacados2 sacados2 = new sacados2();
            sacados2.id = id;
            return sacados2;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOME
        {
            get
            {
                return _NOME;
            }
            set
            {
                OnNOMEChanging(value);
                ReportPropertyChanging("NOME");
                _NOME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOME");
                OnNOMEChanged();
            }
        }
        private global::System.String _NOME;
        partial void OnNOMEChanging(global::System.String value);
        partial void OnNOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SOBRENOME
        {
            get
            {
                return _SOBRENOME;
            }
            set
            {
                OnSOBRENOMEChanging(value);
                ReportPropertyChanging("SOBRENOME");
                _SOBRENOME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SOBRENOME");
                OnSOBRENOMEChanged();
            }
        }
        private global::System.String _SOBRENOME;
        partial void OnSOBRENOMEChanging(global::System.String value);
        partial void OnSOBRENOMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CPF
        {
            get
            {
                return _CPF;
            }
            set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private Nullable<global::System.Double> _CPF;
        partial void OnCPFChanging(Nullable<global::System.Double> value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TIPO_ENDEREÇO_RESIDENCIAL
        {
            get
            {
                return _TIPO_ENDEREÇO_RESIDENCIAL;
            }
            set
            {
                OnTIPO_ENDEREÇO_RESIDENCIALChanging(value);
                ReportPropertyChanging("TIPO_ENDEREÇO_RESIDENCIAL");
                _TIPO_ENDEREÇO_RESIDENCIAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TIPO_ENDEREÇO_RESIDENCIAL");
                OnTIPO_ENDEREÇO_RESIDENCIALChanged();
            }
        }
        private global::System.String _TIPO_ENDEREÇO_RESIDENCIAL;
        partial void OnTIPO_ENDEREÇO_RESIDENCIALChanging(global::System.String value);
        partial void OnTIPO_ENDEREÇO_RESIDENCIALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ENDEREÇO_RESIDENCIAL
        {
            get
            {
                return _ENDEREÇO_RESIDENCIAL;
            }
            set
            {
                OnENDEREÇO_RESIDENCIALChanging(value);
                ReportPropertyChanging("ENDEREÇO_RESIDENCIAL");
                _ENDEREÇO_RESIDENCIAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ENDEREÇO_RESIDENCIAL");
                OnENDEREÇO_RESIDENCIALChanged();
            }
        }
        private global::System.String _ENDEREÇO_RESIDENCIAL;
        partial void OnENDEREÇO_RESIDENCIALChanging(global::System.String value);
        partial void OnENDEREÇO_RESIDENCIALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NÚMERO_RESIDENCIAL
        {
            get
            {
                return _NÚMERO_RESIDENCIAL;
            }
            set
            {
                OnNÚMERO_RESIDENCIALChanging(value);
                ReportPropertyChanging("NÚMERO_RESIDENCIAL");
                _NÚMERO_RESIDENCIAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NÚMERO_RESIDENCIAL");
                OnNÚMERO_RESIDENCIALChanged();
            }
        }
        private global::System.String _NÚMERO_RESIDENCIAL;
        partial void OnNÚMERO_RESIDENCIALChanging(global::System.String value);
        partial void OnNÚMERO_RESIDENCIALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMPLEMENTO_RESIDENCIAL
        {
            get
            {
                return _COMPLEMENTO_RESIDENCIAL;
            }
            set
            {
                OnCOMPLEMENTO_RESIDENCIALChanging(value);
                ReportPropertyChanging("COMPLEMENTO_RESIDENCIAL");
                _COMPLEMENTO_RESIDENCIAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COMPLEMENTO_RESIDENCIAL");
                OnCOMPLEMENTO_RESIDENCIALChanged();
            }
        }
        private global::System.String _COMPLEMENTO_RESIDENCIAL;
        partial void OnCOMPLEMENTO_RESIDENCIALChanging(global::System.String value);
        partial void OnCOMPLEMENTO_RESIDENCIALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C_BAIRRO_RESIDENCIAL
        {
            get
            {
                return _C_BAIRRO_RESIDENCIAL;
            }
            set
            {
                OnC_BAIRRO_RESIDENCIALChanging(value);
                ReportPropertyChanging("C_BAIRRO_RESIDENCIAL");
                _C_BAIRRO_RESIDENCIAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C_BAIRRO_RESIDENCIAL");
                OnC_BAIRRO_RESIDENCIALChanged();
            }
        }
        private global::System.String _C_BAIRRO_RESIDENCIAL;
        partial void OnC_BAIRRO_RESIDENCIALChanging(global::System.String value);
        partial void OnC_BAIRRO_RESIDENCIALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CIDADE_RESIDENCIAL
        {
            get
            {
                return _CIDADE_RESIDENCIAL;
            }
            set
            {
                OnCIDADE_RESIDENCIALChanging(value);
                ReportPropertyChanging("CIDADE_RESIDENCIAL");
                _CIDADE_RESIDENCIAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CIDADE_RESIDENCIAL");
                OnCIDADE_RESIDENCIALChanged();
            }
        }
        private global::System.String _CIDADE_RESIDENCIAL;
        partial void OnCIDADE_RESIDENCIALChanging(global::System.String value);
        partial void OnCIDADE_RESIDENCIALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UF_RESIDENCIAL
        {
            get
            {
                return _UF_RESIDENCIAL;
            }
            set
            {
                OnUF_RESIDENCIALChanging(value);
                ReportPropertyChanging("UF_RESIDENCIAL");
                _UF_RESIDENCIAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UF_RESIDENCIAL");
                OnUF_RESIDENCIALChanged();
            }
        }
        private global::System.String _UF_RESIDENCIAL;
        partial void OnUF_RESIDENCIALChanging(global::System.String value);
        partial void OnUF_RESIDENCIALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CEP_RESIDENCIAL
        {
            get
            {
                return _CEP_RESIDENCIAL;
            }
            set
            {
                OnCEP_RESIDENCIALChanging(value);
                ReportPropertyChanging("CEP_RESIDENCIAL");
                _CEP_RESIDENCIAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CEP_RESIDENCIAL");
                OnCEP_RESIDENCIALChanged();
            }
        }
        private global::System.String _CEP_RESIDENCIAL;
        partial void OnCEP_RESIDENCIALChanging(global::System.String value);
        partial void OnCEP_RESIDENCIALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TELEFONE_COMERCIAL
        {
            get
            {
                return _TELEFONE_COMERCIAL;
            }
            set
            {
                OnTELEFONE_COMERCIALChanging(value);
                ReportPropertyChanging("TELEFONE_COMERCIAL");
                _TELEFONE_COMERCIAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TELEFONE_COMERCIAL");
                OnTELEFONE_COMERCIALChanged();
            }
        }
        private global::System.String _TELEFONE_COMERCIAL;
        partial void OnTELEFONE_COMERCIALChanging(global::System.String value);
        partial void OnTELEFONE_COMERCIALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TELEFONE_RESIDENCIAL
        {
            get
            {
                return _TELEFONE_RESIDENCIAL;
            }
            set
            {
                OnTELEFONE_RESIDENCIALChanging(value);
                ReportPropertyChanging("TELEFONE_RESIDENCIAL");
                _TELEFONE_RESIDENCIAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TELEFONE_RESIDENCIAL");
                OnTELEFONE_RESIDENCIALChanged();
            }
        }
        private global::System.String _TELEFONE_RESIDENCIAL;
        partial void OnTELEFONE_RESIDENCIALChanging(global::System.String value);
        partial void OnTELEFONE_RESIDENCIALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CELULAR
        {
            get
            {
                return _CELULAR;
            }
            set
            {
                OnCELULARChanging(value);
                ReportPropertyChanging("CELULAR");
                _CELULAR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CELULAR");
                OnCELULARChanged();
            }
        }
        private Nullable<global::System.Double> _CELULAR;
        partial void OnCELULARChanging(Nullable<global::System.Double> value);
        partial void OnCELULARChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email1
        {
            get
            {
                return _email1;
            }
            set
            {
                Onemail1Changing(value);
                ReportPropertyChanging("email1");
                _email1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email1");
                Onemail1Changed();
            }
        }
        private global::System.String _email1;
        partial void Onemail1Changing(global::System.String value);
        partial void Onemail1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email2
        {
            get
            {
                return _email2;
            }
            set
            {
                Onemail2Changing(value);
                ReportPropertyChanging("email2");
                _email2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email2");
                Onemail2Changed();
            }
        }
        private global::System.String _email2;
        partial void Onemail2Changing(global::System.String value);
        partial void Onemail2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email3
        {
            get
            {
                return _email3;
            }
            set
            {
                Onemail3Changing(value);
                ReportPropertyChanging("email3");
                _email3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email3");
                Onemail3Changed();
            }
        }
        private global::System.String _email3;
        partial void Onemail3Changing(global::System.String value);
        partial void Onemail3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _status;
        partial void OnstatusChanging(Nullable<global::System.Boolean> value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String obs
        {
            get
            {
                return _obs;
            }
            set
            {
                OnobsChanging(value);
                ReportPropertyChanging("obs");
                _obs = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("obs");
                OnobsChanged();
            }
        }
        private global::System.String _obs;
        partial void OnobsChanging(global::System.String value);
        partial void OnobsChanged();

        #endregion

    
    }

    #endregion

    
}
